### ISSUE TITLE
ls --color=never 

### ISSUE THREAD

**Issue by dipcore** [gryf/mc_adbfs#1]
Please add **--color=never** param to **ls**, 
otherwise file names contain color codes:

.[1;34m..[0m  
.[1;34m...[0m  
.[1;34macct.[0m  
.[1;34mcache.[0m  
.[1;34mdata.[0m  
.[1;34mdev.[0m  
.[1;34mmnt.[0m  
.[1;34mproc.[0m  

etc

**Comment by gryf** [comment]
What kind of *box are you happen to have on your device? On my device, starting from CM 13 busybox was replaced by toolbox.

**Comment by dipcore** [comment]
Yes, you're right I have toolbox too (It's android TV device). It seems like that happened because I installed a full version of busybox with all links, so now it uses ls from busybox by default.

It may be a good idea to have a parameter in the plugin config for **ls**

**Comment by gryf** [comment]
Yup, I can provide another config option for that. Stay tuned :)

**Comment by gryf** [comment]
Done with latest commit.
